#!/bin/bash

OPENBOR_CPU_MASK=03
OPENBOR_EXE_NAME="OpenBOR"
OPENBOR_HOME_DIR="/media/fat/OpenBOR"
OPENBOR_WORK_DIR="$OPENBOR_HOME_DIR/CRT"
OPENBOR_OPTIONS="--root-dir=$OPENBOR_WORK_DIR"
LIB_PATH="${OPENBOR_HOME_DIR}/Libs:${OPENBOR_HOME_DIR}/Libs/pulseaudio"

# CGA Resolution (Arcade Monitors)
vmode -r 320 240 rgb32 > /dev/null 2>&1

export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${LIB_PATH}"

cd ${OPENBOR_HOME_DIR}
taskset ${OPENBOR_CPU_MASK} ${OPENBOR_HOME_DIR}/${OPENBOR_EXE_NAME} ${OPENBOR_OPTIONS} > /dev/null 2>&1
